name: world_movie_trailer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3                    # Latest stable version for HTTP requests
  html: ^0.15.0                    # For working with HTML content
  intl: ^0.17.0                    # For internationalization and formatting
  cupertino_icons: ^1.0.6          # iOS-style icons for your app
  firebase_core: ^3.3.0            # Firebase core library
  firebase_storage: ^12.1.3        # Firebase storage for file handling
  youtube_player_flutter: ^8.1.0   # Adjusted to the latest stable version
  hive: ^2.2.3                     # Non-relational database for Flutter
  hive_flutter: ^1.1.0             # Flutter-specific Hive integration
  provider: ^6.0.0
  url_launcher: ^6.2.4
  simple_animations: ^5.0.2 

dependency_overrides:
  flutter_math_fork: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dark/deco_world_map_DT_xxhdpi.png
    - assets/images/dark/deco_film_reel_DT_xxhdpi.png
    - assets/images/dark/icon_config_DT_xxhdpi.png
    - assets/images/dark/icon_reorder_DT_xxhdpi.png
    - assets/images/light/deco_world_map_LT_xxhdpi.png
    - assets/images/light/deco_film_reel_LT_xxhdpi.png
    - assets/images/light/icon_config_LT_xxhdpi.png
    - assets/images/light/icon_reorder_LT_xxhdpi.png