name: world_movie_trailer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+16

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2                    # Latest stable version for HTTP requests
  html: ^0.15.0                    # For working with HTML content
  intl: ^0.19.0                    # For internationalization and formatting
  cupertino_icons: ^1.0.6          # iOS-style icons for your app
  firebase_core: ^3.5.0            # Firebase core library
  firebase_storage: ^12.1.3        # Firebase storage for file handling
  youtube_player_flutter: ^9.1.0   # Adjusted to the latest stable version
  hive: ^2.2.3                     # Non-relational database for Flutter
  hive_flutter: ^1.1.0             # Flutter-specific Hive integration
  provider: ^6.0.0
  url_launcher: ^6.3.0
  simple_animations: ^5.0.2 
  video_player: ^2.5.1  
  chewie: ^1.3.4     
  share_plus: ^10.0.2
  google_mobile_ads: ^5.1.0
  amplitude_flutter: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: true
  ios: true
  image_path_android: "icons/playstore.png"
  image_path_ios: "icons/appstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/dark/deco_world_map_DT_xxhdpi.png
    - assets/images/dark/deco_film_reel_DT_xxhdpi.png
    - assets/images/dark/icon_config_DT_xxhdpi.png
    - assets/images/dark/icon_reorder_DT_xxhdpi.png
    - assets/images/dark/logo_sil_white_1024.png
    - assets/images/dark/blank_DT_xxhdpi.png
    - assets/images/dark/loading_DT_xxhdpi.png
    - assets/images/dark/icon_menu_DT_xxhdpi.png
    - assets/images/dark/icon_like_DT_xxhdpi.png
    - assets/images/dark/icon_dislike_DT_xxhdpi.png
    - assets/images/dark/icon_bookmark_fill_DT_xxhdpi.png
    - assets/images/dark/icon_bookmark_DT_xxhdpi.png
    - assets/images/dark/icon_memo_DT_xxhdpi.png
    - assets/images/dark/icon_drag_handle_DT_xxhdpi.png
    - assets/images/dark/icon_like_fill_DT_xxhdpi.png
    - assets/images/dark/icon_dislike_fill_DT_xxhdpi.png
    - assets/images/light/deco_world_map_LT_xxhdpi.png
    - assets/images/light/deco_film_reel_LT_xxhdpi.png
    - assets/images/light/icon_config_LT_xxhdpi.png
    - assets/images/light/icon_reorder_LT_xxhdpi.png
    - assets/images/light/logo_sil_black_1024.png
    - assets/images/light/blank_LT_xxhdpi.png
    - assets/images/light/loading_LT_xxhdpi.png
    - assets/images/light/icon_menu_LT_xxhdpi.png
    - assets/images/light/icon_like_LT_xxhdpi.png
    - assets/images/light/icon_dislike_LT_xxhdpi.png
    - assets/images/light/icon_bookmark_fill_LT_xxhdpi.png
    - assets/images/light/icon_bookmark_LT_xxhdpi.png
    - assets/images/light/icon_memo_LT_xxhdpi.png
    - assets/images/light/icon_drag_handle_LT_xxhdpi.png
    - assets/images/light/icon_like_fill_LT_xxhdpi.png
    - assets/images/light/icon_dislike_fill_LT_xxhdpi.png
    - assets/images/SIL_logo_h_xxhdpi.png
    - assets/images/deco_film_reel_02_DT_xxhdpi.png