// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIZsSc5DbyW2ZIXzOKmV8wuO7xa89Z5mU',
    appId: '1:1034047577753:ios:01c81d69567105c2dfa208',
    messagingSenderId: '1034047577753',
    projectId: 'world-movie-trailer-v2',
    storageBucket: 'world-movie-trailer-v2.firebasestorage.app',
    iosBundleId: 'com.sunnyinnolab.worldMovieTrailer',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5R97bRJpXoiL2lhAgi7h7KJDbgA1l_dE',
    appId: '1:1034047577753:android:7ae2c8f1676bc413dfa208',
    messagingSenderId: '1034047577753',
    projectId: 'world-movie-trailer-v2',
    storageBucket: 'world-movie-trailer-v2.firebasestorage.app',
  );
}
