// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMubXNoFSBtIZOH_uD3zR7cmMEP_keyjA',
    appId: '1:917295366628:web:7d4255ebcc6aeb4a0cc7f1',
    messagingSenderId: '917295366628',
    projectId: 'world-movie-trailer',
    authDomain: 'world-movie-trailer.firebaseapp.com',
    storageBucket: 'world-movie-trailer.appspot.com',
    measurementId: 'G-NT1KH6LBJ1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA323GF95NhZ7QjhMZKit5uF1IJaVeTgY8',
    appId: '1:917295366628:ios:18f419886a592f220cc7f1',
    messagingSenderId: '917295366628',
    projectId: 'world-movie-trailer',
    storageBucket: 'world-movie-trailer.appspot.com',
    iosBundleId: 'com.example.worldMovieTrailer',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK6OJdTlKcu-lQ0WVX8lw3Zs8RZeP_Xg0',
    appId: '1:917295366628:android:ce236cf93580522d0cc7f1',
    messagingSenderId: '917295366628',
    projectId: 'world-movie-trailer',
    storageBucket: 'world-movie-trailer.appspot.com',
  );

}